### ISSUE TITLE
Support for multiple node + yarn versions

### ISSUE THREAD

**Issue by ghost** [neciu/node-yarn#1]
Hey,
the official node image (https://hub.docker.com/r/library/node/) support multiple versions.

I would be nice if this image could support multiple node versions + yarn versions too for better backwards compatibility.

The tag structure could be _node-6.9.1-yarn-0.16.1_

It would clarify what version the image contains.

**Comment by neciu** [comment]
Great idea. I'll add it soon!

**Comment by neciu** [comment]
Hi @Ghostium!
I've updated the project to support multiple Node and Yarn versions according to naming proposed by you. 

You can find more info in [readme](../blob/master/README.md) and already build images [here](https://hub.docker.com/r/netczuk/node-yarn/tags/).

Feel free to make merge requests with other versions of Node/Yarn.
