### ISSUE TITLE
Automated Builds

### ISSUE THREAD

**Issue by ghost** [neciu/node-yarn#4]
Hey,
automated builds would reduce the time spent maintaining this repository.

Example:
1. Script, which downloads version data from npm API (https://registry.npmjs.org/yarn in key "versions") and docker API (https://registry.hub.docker.com/v1/repositories/node/tags but using v2 instead v1).
2. Script that checks if any new versions (based on the data fetched before) are out and build & upload these
3. Cron Webhook that invokes 1 and 2 every 24h

**Comment by jonaskello** [comment]
This is a really good idea considering the latest built is 0.18.1 and 0.20.3 is out. Let me know if I can help on this. I think I could do the scripts but I'm not sure how and where to setup the cron webhook.

**Comment by ghost** [comment]
I thought about using a lambda service with cron capabilities. (AWS Lambda, Azure Functions, Google Cloud Functions, hook.io, stdlib, webtask & other).

I recommend picking a provider which has a free amount of compute seconds built in, so there no monthly costs. (Ex. https://aws.amazon.com/de/lambda/pricing/)

However, this script is required to be installed by the owner, as the secret for the Github master repo access is required to trigger the rebuild of the images.

Example:

Create a NodeJS script, with the configurable variables; Github repo url, Github name & password / RSA-key. Then check the yarn-versions.json and node-versions.json from the master branch of the Github repo url, against the info from the npm and Docker api.
If there are new versions use the Github Account to commit & push the new json files to the master of your test repository. These should trigger the Docker CI itself. If you are done the repo owner only has to replace the repo url & account and upload the script to his preferred provider.

**Comment by jonaskello** [comment]
I found a way to use the regular node images instead. In [this blog](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) check this section:

> Did you know that Yarn is also distributed as a single bundle JS file in releases that can be used on CI systems without internet access?

Yarn is actually released as a single js file and you can check `yarn.js` into git and then use `node ./yarn.js` instead of just `yarn`. In my case I used this image for CI builds, but now I can use the regular node image instead and the version of yarn will be whatever yarn.js I checked into my git repo. Still would be nice to have an image that included both node and yarn for other scenarios though.

**Comment by neciu** [comment]
Hi there!

Sorry for big delay in response.

I have important message for you guys: since a month ago or so yarn is added to node images by default - so there is no need to maintain these images any more - so I'm deprecating this project.

Thanks,
neciu

**Comment by jonaskello** [comment]
Wow, that's good news! Thanks for sharing!
